site_name: My Site
theme:
  name: material
nav:
  - Home: index.md
  - About: about.md
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
